# Generated by Django 6.0.2 on 2026-02-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Return Requested', 'Return Requested'), ('Pending Approval', 'Pending Approval'), ('Refund Processed', 'Refund Processed'), ('Return Rejected', 'Return Rejected')], default='Delivered', max_length=50),
        ),
    ]
